apiVersion: sql.cnrm.cloud.google.com/v1beta1
 
kind: SQLInstance
 
metadata:
         
 name: storedb-instance-shubhika
           
spec:
                   
  databaseVersion: MYSQL_5_7
                     
  region: us-central1
                       
  settings:
                                 
     tier: db-f1-micro
                                    

