{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "machineinfo.serviceAccountName" . }}
  labels:
{{ include "machineinfo.labels" . | indent 4 }}
{{- end -}}
